/* Câu 27 */
SELECT COUNT(*) AS SLGV, SUM(LUONG) AS TONG_LUONG
FROM GIAOVIEN

/* Câu 28 */
SELECT MABM, COUNT(*) AS SLGV, AVG(LUONG) AS LUONG_TB
FROM GIAOVIEN
GROUP BY MABM

/* Câu 29 */
SELECT CHUDE.TENCD, COUNT (DETAI.MADT) AS SL_DT
FROM CHUDE LEFT JOIN DETAI ON CHUDE.MACD = DETAI.MACD
GROUP BY CHUDE.MACD, CHUDE.TENCD

/* Câu 30 */
SELECT HOTEN, COUNT (DISTINCT THAMGIADT.MADT) AS SL_DT
FROM GIAOVIEN LEFT JOIN THAMGIADT ON GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

/* Câu 31 */
SELECT HOTEN, COUNT (DETAI.GVCNDT) AS SL_DT_CN
FROM GIAOVIEN LEFT JOIN DETAI ON GIAOVIEN.MAGV = DETAI.GVCNDT
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

/* Câu 32 */
SELECT HOTEN, COUNT (NGUOITHAN.TEN)
FROM GIAOVIEN LEFT JOIN NGUOITHAN ON GIAOVIEN.MAGV = NGUOITHAN.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN

/* Câu 33 */
SELECT GIAOVIEN.HOTEN
FROM GIAOVIEN, THAMGIADT
WHERE GIAOVIEN.MAGV = THAMGIADT.MAGV
GROUP BY GIAOVIEN.MAGV, GIAOVIEN.HOTEN
HAVING COUNT (DISTINCT THAMGIADT.MADT) >= 3

/* Câu 34 */
SELECT COUNT(DISTINCT THAMGIADT.MAGV) AS SL_GV_THAMGIA_UNGDUNGHHXANH
FROM DETAI, THAMGIADT
WHERE DETAI.TENDT = N'Ứng dụng hoá học xanh' AND DETAI.MADT = THAMGIADT.MADT
GROUP BY THAMGIADT.MADT