/* Câu 17 */
SELECT CHUYENBAY.SBDEN, COUNT (LICHBAY.NGAYDI) AS SL_CHUYENBAY_HACANH
FROM CHUYENBAY LEFT JOIN LICHBAY ON CHUYENBAY.MACB = LICHBAY.MACB
GROUP BY CHUYENBAY.SBDEN
ORDER BY CHUYENBAY.SBDEN ASC

/* Câu 18 */
SELECT CHUYENBAY.SBDI, COUNT (LICHBAY.NGAYDI) AS SL_CHUYENBAY_CATCANH
FROM CHUYENBAY LEFT JOIN LICHBAY ON CHUYENBAY.MACB = LICHBAY.MACB
GROUP BY CHUYENBAY.SBDI
ORDER BY CHUYENBAY.SBDI ASC

/* Câu 19 */
SELECT CHUYENBAY.SBDI, LICHBAY.NGAYDI, COUNT (LICHBAY.NGAYDI) AS SL_CHUYENBAY
FROM CHUYENBAY, LICHBAY
WHERE CHUYENBAY.MACB = LICHBAY.MACB
GROUP BY CHUYENBAY.SBDI, LICHBAY.NGAYDI

/* Câu 20 */
SELECT CHUYENBAY.SBDEN, LICHBAY.NGAYDI, COUNT (LICHBAY.NGAYDI) AS SL_CHUYENBAY
FROM CHUYENBAY, LICHBAY
WHERE CHUYENBAY.MACB = LICHBAY.MACB
GROUP BY CHUYENBAY.SBDEN, LICHBAY.NGAYDI

/* Câu 21 */
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, COUNT (A.MANV) AS SL_NV_K_LA_PHICONG
FROM PHANCONG LEFT JOIN (SELECT * FROM NHANVIEN WHERE NHANVIEN.LOAINV = 0) AS A ON PHANCONG.MANV = A.MANV
GROUP BY PHANCONG.MACB, PHANCONG.NGAYDI

/* Câu 22 */
SELECT COUNT (LICHBAY.MACB)
FROM LICHBAY, CHUYENBAY
WHERE LICHBAY.MACB = CHUYENBAY.MACB AND CHUYENBAY.SBDI = 'MIA' AND DATEDIFF(D, LICHBAY.NGAYDI, '11/01/2000') = 0

/* Câu 23 */
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, COUNT (PHANCONG.MANV) AS SL_NV
FROM PHANCONG
GROUP BY PHANCONG.MACB, PHANCONG.NGAYDI
ORDER BY SL_NV DESC

/* Câu 24 */
SELECT DATCHO.MACB, DATCHO.NGAYDI, COUNT (DATCHO.MAKH) AS SL_DATCHO
FROM DATCHO
GROUP BY DATCHO.MACB, DATCHO.NGAYDI
ORDER BY SL_DATCHO DESC

/* Câu 25 */
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, SUM(NHANVIEN.LUONG) AS TONGLUONG
FROM PHANCONG, NHANVIEN
WHERE PHANCONG.MANV = NHANVIEN.MANV
GROUP BY PHANCONG.MACB, PHANCONG.NGAYDI
ORDER BY TONGLUONG ASC

/* Câu 26 */
SELECT AVG(LUONG)AS LUONGTB_NV_K_LA_PHICONG FROM NHANVIEN WHERE NHANVIEN.LOAINV = 0

/* Câu 27 */
SELECT AVG(LUONG)AS LUONGTB_NV_LA_PHICONG FROM NHANVIEN WHERE NHANVIEN.LOAINV = 1

/* Câu 28 */
SELECT LICHBAY.MALOAI, COUNT (LICHBAY.NGAYDI) AS SL_HACANH_ORD
FROM CHUYENBAY, LICHBAY
WHERE CHUYENBAY.SBDEN = 'ORD' AND CHUYENBAY.MACB = LICHBAY.MACB
GROUP BY LICHBAY.MALOAI

/* Câu 29 */
SELECT CHUYENBAY.SBDI, COUNT(CHUYENBAY.MACB) AS SL_CHUYENBAY
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, CHUYENBAY.GIODI, '10:00') <= 0 AND DATEDIFF(MINUTE, CHUYENBAY.GIODI, '22:00') >= 0
GROUP BY CHUYENBAY.SBDI
HAVING COUNT (CHUYENBAY.MACB) > 2

/* Câu 30 */
SELECT NHANVIEN.TEN
FROM NHANVIEN, PHANCONG
WHERE NHANVIEN.MANV = PHANCONG.MANV AND NHANVIEN.LOAINV = 1
GROUP BY NHANVIEN.MANV, NHANVIEN.TEN, PHANCONG.NGAYDI
HAVING COUNT(PHANCONG.NGAYDI) >= 2

/* Câu 31 */
SELECT DATCHO.MACB, DATCHO.NGAYDI
FROM DATCHO
GROUP BY DATCHO.MACB, DATCHO.NGAYDI
HAVING COUNT (DATCHO.MAKH) < 3

/* Câu 32 */
SELECT LICHBAY.SOHIEU, LICHBAY.MALOAI
FROM LICHBAY, PHANCONG
WHERE LICHBAY.MACB = PHANCONG.MACB AND PHANCONG.NGAYDI = LICHBAY.NGAYDI AND PHANCONG.MANV = '1001'
GROUP BY LICHBAY.SOHIEU, LICHBAY.MALOAI
HAVING COUNT(LICHBAY.NGAYDI) > 2

/* Câu 33 */
SELECT HANGSX, COUNT (MALOAI) AS SO_LOAI
FROM LOAIMB
GROUP BY HANGSX