-- CSDL QuanLyDeTai
USE QuanLyDeTai


--Q58 
-- EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CD.MACD
					FROM CHUDE CD
					EXCEPT ( SELECT DT.MACD
							FROM THAMGIADT TG,DETAI DT
							WHERE GV.MAGV=TG.MAGV AND TG.MADT =DT.MADT ))
--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM CHUDE CD
					WHERE NOT EXISTS ( SELECT *
							FROM THAMGIADT TG,DETAI DT
							WHERE GV.MAGV=TG.MAGV AND TG.MADT =DT.MADT AND DT.MACD=CD.MACD))	
--COUNT 

SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV =TG.MAGV AND TG.MADT= DT.MADT
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MACD) = ( SELECT COUNT(*)
									FROM CHUDE)




--Q59
-- EXCEPT

SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
					FROM GIAOVIEN GV
					WHERE GV.MABM='HTTT'
					EXCEPT 
					SELECT	TG.MAGV
					FROM	THAMGIADT TG
					WHERE TG.MADT=DT.MADT)

--NOT EXISTS 
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS (SELECT *
					FROM GIAOVIEN GV
					WHERE GV.MABM='HTTT'
					AND NOT EXISTS ( 
					SELECT	*
					FROM	THAMGIADT TG
					WHERE TG.MADT=DT.MADT and TG.MAGV=GV.MAGV))

--COUNT 
SELECT DT.TENDT
FROM DETAI DT, GIAOVIEN GV, THAMGIADT TG 
WHERE TG.MAGV=GV.MAGV AND TG.MADT = DT.MADT AND GV.MABM ='HTTT'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT GV.MAGV ) = ( SELECT COUNT(*) 
									FROM GIAOVIEN 
									WHERE GIAOVIEN.MABM='HTTT')


--Q60
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM = BM.MABM AND BM.TENBM=N'Hệ thống thông tin'
					EXCEPT 
					SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT=DT.MADT )

--NOT EXISTS 

SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT *
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM = BM.MABM AND BM.TENBM=N'Hệ thống thông tin'
					AND NOT EXISTS ( 
					SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT=DT.MADT AND TG.MAGV=GV.MAGV))

--COUNT 

SELECT DT.TENDT
FROM DETAI DT,THAMGIADT TG, GIAOVIEN GV,BOMON BM
WHERE TG.MADT=DT.MADT AND TG.MAGV=GV.MAGV AND GV.MABM = BM.MABM AND BM.TENBM=N'Hệ thống thông tin'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT TG.MAGV) = (SELECT COUNT(*)
									FROM GIAOVIEN , BOMON
									WHERE GIAOVIEN.MABM = BOMON.MABM  AND BOMON.TENBM=N'Hệ thống thông tin')


--Q61 
--EXCEPT
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
					FROM  DETAI DT
					WHERE DT.MACD='QLGD'
					EXCEPT	
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV=GV.MAGV)
--NOT EXISTS 
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM  DETAI DT
					WHERE DT.MACD='QLGD'
					AND NOT EXISTS 
					(SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV=GV.MAGV AND TG.MADT=DT.MADT))
-- COUNT 
SELECT GV.MAGV, COUNT(DISTINCT TG.MADT)
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV= TG.MAGV AND TG.MADT = DT.MADT AND DT.MACD='QLGD'
GROUP BY GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) =(SELECT COUNT(*)
									FROM DETAI
									WHERE DETAI.MACD='QLGD')

--Q62
--EXCEPT 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT TG.MADT
					FROM THAMGIADT TG, GIAOVIEN GV
					WHERE TG.MAGV=GV.MAGV AND GV.HOTEN =N'Trần Trà Hương'
					EXCEPT 
					SELECT TG2.MADT
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = GV.MAGV) AND GV.HOTEN NOT LIKE N'Trần Trà Hương'
--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM THAMGIADT TG, GIAOVIEN GV2
					WHERE TG.MAGV=GV2.MAGV AND GV2.HOTEN =N'Trần Trà Hương'
					AND NOT EXISTS ( 
					SELECT *
					FROM THAMGIADT TG2
					WHERE TG2.MAGV = GV.MAGV AND TG2.MADT=TG.MADT)) AND GV.HOTEN NOT LIKE N'Trần Trà Hương'
--COUNT

SELECT GV.HOTEN
FROM GIAOVIEN GV , THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
AND TG.MADT IN ( SELECT THAMGIADT.MADT
					FROM THAMGIADT, GIAOVIEN
					WHERE GIAOVIEN.HOTEN =N'Trần Trà Hương'AND THAMGIADT.MAGV=GIAOVIEN.MAGV)
GROUP BY GV.MAGV,GV.HOTEN
HAVING COUNT(DISTINCT TG.MADT) =(SELECT COUNT(DISTINCT THAMGIADT.MADT)
					FROM THAMGIADT, GIAOVIEN
					WHERE GIAOVIEN.HOTEN =N'Trần Trà Hương'AND THAMGIADT.MAGV=GIAOVIEN.MAGV) AND GV.HOTEN NOT LIKE N'Trần Trà Hương'

--Q63
--EXCEPT
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM=BM.MABM AND BM.TENBM =N'Hoá hữu cơ'
					EXCEPT
					SELECT TG.MAGV
					 FROM THAMGIADT TG
					WHERE TG.MADT= DT.MADT ) 

--NOT EXISTS 
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT *
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM=BM.MABM AND BM.TENBM =N'Hoá hữu cơ'
					AND NOT EXISTS (
					SELECT *
					 FROM THAMGIADT TG
					WHERE TG.MADT= DT.MADT AND TG.MAGV=GV.MAGV) )

--COUNT 
SELECT DT.TENDT
FROM DETAI DT,THAMGIADT TG, GIAOVIEN GV, BOMON BM
WHERE TG.MAGV=GV.MAGV AND TG.MADT = DT.MADT	 AND GV.MABM=BM.MABM AND BM.TENBM=N'Hoá hữu cơ'
GROUP BY DT.TENDT
HAVING COUNT(DISTINCT  GV.MAGV) =(  SELECT COUNT(*)
					FROM GIAOVIEN GV, BOMON BM
					WHERE GV.MABM=BM.MABM AND BM.TENBM =N'Hoá hữu cơ')

--Q64
--EXCEPT 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.SOTT
					FROM CONGVIEC CV
					WHERE CV.MADT ='006'
					EXCEPT 
					SELECT TG.STT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND TG.MADT='006')

--NOT EXISTS 

SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM CONGVIEC CV
					WHERE CV.MADT ='006'
					AND NOT EXISTS ( 
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND CV.MADT=TG.MADT AND CV.SOTT = TG.STT))

--COUNT 
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG
WHERE GV.MAGV = TG.MAGV AND TG.MADT ='006'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(*)
					FROM CONGVIEC CV
					WHERE CV.MADT ='006') 


--Q65
--EXCEPT 
SELECT GV.HOTEN
FROM	GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ'
					EXCEPT 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV )
					
-- NOT EXISTS 
SELECT GV.HOTEN
FROM	GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ'
					AND NOT EXISTS ( 
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT))
--COUNT 
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT,CHUDE CD
WHERE GV.MAGV =TG.MAGV AND TG.MADT = DT.MADT AND DT.MACD=CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ'
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT DT.MADT) = ( SELECT COUNT(*)
					FROM DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Ứng dụng công nghệ')


--Q66
--EXCEPT 
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS ( SELECT DT.MADT
					FROM	DETAI DT , GIAOVIEN GV2
					WHERE DT.GVCNDT =GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương'
					EXCEPT 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV1.MAGV )
-- NOT EXISTS 
SELECT GV1.HOTEN
FROM GIAOVIEN GV1
WHERE NOT EXISTS ( SELECT *
					FROM	DETAI DT , GIAOVIEN GV2
					WHERE DT.GVCNDT =GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương'
					AND NOT EXISTS (
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV1.MAGV AND DT.MADT = TG.MADT))

--COUNT 
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV AND TG.MADT =DT.MADT
GROUP BY GV.HOTEN , GV.MAGV
HAVING COUNT (DISTINCT DT.MADT ) = (SELECT COUNT(*)
					FROM	DETAI DT , GIAOVIEN GV2
					WHERE DT.GVCNDT =GV2.MAGV AND GV2.HOTEN = N'Trần Trà Hương')
--Q67
--EXCEPT 
SELECT DT.TENDT
FROM	DETAI DT
WHERE NOT EXISTS (SELECT GV.MAGV
					FROM	GIAOVIEN GV, BOMON BM, KHOA K
					WHERE GV.MABM=BM.MABM AND BM.MAKHOA=K.MAKHOA AND K.MAKHOA='CNTT'
					EXCEPT 
					SELECT GV2.MAGV
					FROM	GIAOVIEN GV2, THAMGIADT TG
					WHERE GV2.MAGV=TG.MAGV AND TG.MADT = DT.MADT )
--NOT EXISTS

SELECT DT.TENDT
FROM	DETAI DT
WHERE NOT EXISTS (SELECT *
					FROM	GIAOVIEN GV, BOMON BM, KHOA K
					WHERE GV.MABM=BM.MABM AND BM.MAKHOA=K.MAKHOA AND K.MAKHOA='CNTT'
					AND NOT EXISTS ( 
					SELECT TG.MAGV
					FROM	 THAMGIADT TG
					WHERE  TG.MADT = DT.MADT AND TG.MAGV=GV.MAGV))	
--COUNT 
SELECT DT.TENDT
FROM	DETAI DT, GIAOVIEN GV, BOMON BM , KHOA K, THAMGIADT TG
WHERE GV.MABM=BM.MABM AND BM.MAKHOA = K.MAKHOA AND GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND K.MAKHOA='CNTT'
GROUP BY DT.TENDT, DT.MADT
HAVING COUNT ( DISTINCT GV.MAGV) = ( SELECT COUNT(*)
					FROM	GIAOVIEN GV, BOMON BM, KHOA K
					WHERE GV.MABM=BM.MABM AND BM.MAKHOA=K.MAKHOA AND K.MAKHOA='CNTT')

--Q68
--EXCEPT
SELECT GV.HOTEN
FROM	 GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.SOTT 
					FROM	CONGVIEC CV, DETAI DT
					WHERE CV.MADT = DT.MADT AND DT.TENDT =N'Nghiên cứu tế bào gốc'
					EXCEPT 
					SELECT TG.STT
					FROM THAMGIADT TG, DETAI DT2
					WHERE TG.MAGV = GV.MAGV AND TG.MADT=DT2.MADT AND DT2.TENDT=N'Nghiên cứu tế bào gốc' )

--NOT EXISTS 
SELECT GV.HOTEN
FROM	 GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM	CONGVIEC CV, DETAI DT
					WHERE CV.MADT = DT.MADT AND DT.TENDT =N'Nghiên cứu tế bào gốc'
					AND NOT EXISTS (
					SELECT *
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV AND TG.MADT=DT.MADT AND CV.SOTT = TG.STT AND DT.TENDT=N'Nghiên cứu tế bào gốc' ))
-- COUNT 
SELECT GV.HOTEN
FROM	 GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.TENDT =N'Nghiên cứu tế bào gốc' 
GROUP BY GV.HOTEN, GV.MAGV
HAVING COUNT(DISTINCT TG.STT) = (SELECT COUNT(*)
					FROM	CONGVIEC CV, DETAI DT
					WHERE CV.MADT = DT.MADT AND DT.TENDT =N'Nghiên cứu tế bào gốc')

--Q69
--EXCEPT
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT DT.MADT
					FROM DETAI DT
					WHERE DT.KINHPHI >100
					EXCEPT 
					SELECT TG.MADT
					FROM	 THAMGIADT TG
					WHERE TG.MAGV	=GV.MAGV)
--NOT EXISTS 
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT *
					FROM DETAI DT
					WHERE DT.KINHPHI >100
					AND NOT EXISTS ( 
					SELECT *
					FROM	 THAMGIADT TG
					WHERE TG.MAGV	=GV.MAGV AND DT.MADT = TG.MADT))
-- COUNT 
SELECT GV.HOTEN
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV=TG.MAGV AND DT.MADT = TG.MADT AND DT.KINHPHI >100
GROUP BY GV.HOTEN,GV.MAGV 
HAVING COUNT ( DISTINCT DT.MADT ) = ( SELECT	COUNT( *)
					FROM DETAI DT
					WHERE DT.KINHPHI >100)
	

--Q70
--EXCEPT 
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV 
					FROM GIAOVIEN GV, BOMON BM, KHOA K
					WHERE GV.MABM = BM.MABM AND BM.MAKHOA	=K.MAKHOA AND K.TENKHOA=N'Sinh học'
					EXCEPT
					SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT = DT.MADT )
-- NOT EXISTS 
SELECT DT.TENDT
FROM DETAI DT
WHERE NOT EXISTS ( SELECT GV.MAGV 
					FROM GIAOVIEN GV, BOMON BM, KHOA K
					WHERE GV.MABM = BM.MABM AND BM.MAKHOA	=K.MAKHOA AND K.TENKHOA=N'Sinh học'
					AND NOT EXISTS (
					SELECT TG.MAGV
					FROM THAMGIADT TG
					WHERE TG.MADT = DT.MADT AND GV.MAGV = TG.MAGV ))
-- COUNT 
SELECT DT.TENDT
FROM DETAI DT, GIAOVIEN GV, THAMGIADT TG, BOMON BM, KHOA K
WHERE DT.MADT= TG.MADT AND TG.MAGV = GV.MAGV AND GV.MABM = BM.MABM AND BM.MAKHOA =K.MAKHOA AND K.TENKHOA = N'Sinh học'
GROUP BY DT.TENDT, DT.MADT	
HAVING COUNT ( DISTINCT GV.MAGV ) = ( SELECT COUNT(GV.MAGV) 
					FROM GIAOVIEN GV, BOMON BM, KHOA K
					WHERE GV.MABM = BM.MABM AND BM.MAKHOA	=K.MAKHOA AND K.TENKHOA=N'Sinh học')

--Q71 
--EXCEPT
SELECT GV.MAGV, GV.HOTEN,GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.SOTT
					FROM CONGVIEC CV, DETAI DT
					WHERE CV.MADT=DT.MADT AND DT.TENDT =N'Ứng dụng hoá học xanh'
					EXCEPT 
					SELECT TG.STT
					FROM THAMGIADT TG ,DETAI DT2
					WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT2.MADT AND DT2.TENDT= N'Ứng dụng hoá học xanh')

--NOT EXISTS 
SELECT GV.MAGV, GV.HOTEN,GV.NGSINH
FROM GIAOVIEN GV
WHERE NOT EXISTS ( SELECT CV.SOTT
					FROM CONGVIEC CV, DETAI DT
					WHERE CV.MADT=DT.MADT AND DT.TENDT =N'Ứng dụng hoá học xanh'
					AND NOT EXISTS ( 
					SELECT TG.STT
					FROM THAMGIADT TG 
					WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT AND DT.TENDT= N'Ứng dụng hoá học xanh'))
--COUNT 
SELECT GV.MAGV, GV.HOTEN,GV.NGSINH
FROM GIAOVIEN GV,  THAMGIADT TG, DETAI DT
WHERE GV.MAGV =  TG.MAGV AND TG.MADT = DT.MADT AND DT.TENDT= N'Ứng dụng hoá học xanh'
GROUP BY GV.MAGV, GV.HOTEN,GV.NGSINH
HAVING COUNT( DISTINCT TG.STT) = (SELECT COUNT(CV.SOTT)
					FROM CONGVIEC CV, DETAI DT
					WHERE CV.MADT=DT.MADT AND DT.TENDT =N'Ứng dụng hoá học xanh')
--Q72 
-- EXCEPT 
SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV, BOMON BM, GIAOVIEN GVQL
WHERE	GV.MABM = BM.MABM AND GV.GVQLCM = GVQL.MAGV AND
 NOT EXISTS (		 SELECT DT.MADT
					FROM  DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Nghiên cứu phát triển'
					EXCEPT 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV )
-- NOT EXISTS 

SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV, BOMON BM, GIAOVIEN GVQL
WHERE	GV.MABM = BM.MABM AND GV.GVQLCM = GVQL.MAGV AND
 NOT EXISTS (		 SELECT DT.MADT
					FROM  DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Nghiên cứu phát triển'
					AND NOT EXISTS ( 
					SELECT TG.MADT
					FROM THAMGIADT TG
					WHERE TG.MAGV = GV.MAGV  AND DT.MADT = TG.MADT))			
-- COUNT 	

SELECT GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN AS GVQL
FROM GIAOVIEN GV, BOMON BM, GIAOVIEN GVQL, THAMGIADT TG, DETAI DT ,CHUDE CD
WHERE	GV.MABM = BM.MABM AND GV.GVQLCM = GVQL.MAGV AND TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT AND DT.MACD = CD.MACD AND CD.TENCD =N'Nghiên cứu phát triển'
GROUP BY GV.MAGV, GV.HOTEN, BM.TENBM, GVQL.HOTEN
HAVING COUNT( DISTINCT DT.MADT ) = (  SELECT COUNT(DT.MADT)
					FROM  DETAI DT, CHUDE CD
					WHERE DT.MACD = CD.MACD AND CD.TENCD =N'Nghiên cứu phát triển')


-- CSDL QuanLyChuyenBay
USE QuanLyChuyenBay

--Q51
--EXCEPT 
SELECT CB.MACB
FROM CHUYENBAY CB
WHERE NOT EXISTS ( SELECT MB.SOHIEU
					FROM	MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX = 'Boeing'
					EXCEPT 
					SELECT LB.SOHIEU
					FROM LICHBAY LB
					WHERE LB.MACB = CB.MACB)

--NOT EXISTS 
SELECT CB.MACB
FROM CHUYENBAY CB
WHERE NOT EXISTS ( SELECT *
					FROM	MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX = 'Boeing'
					AND NOT EXISTS ( 
					SELECT *
					FROM LICHBAY LB
					WHERE LB.MACB = CB.MACB AND MB.SOHIEU = LB.SOHIEU))
-- COUNT 
SELECT CB.MACB
FROM CHUYENBAY CB, LICHBAY LB, MAYBAY MB, LOAIMB LMB
WHERE CB.MACB = LB.MACB AND LB.SOHIEU = MB.SOHIEU AND MB.MALOAI =	LMB.MALOAI AND LMB.HANGSX = 'Boeing'
GROUP BY CB.MACB 
HAVING COUNT (DISTINCT MB.SOHIEU ) = ( SELECT COUNT(*)
					FROM	MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX = 'Boeing')

--Q52
--EXCEPT

SELECT NV.MANV, NV.TEN
FROM NHANVIEN NV
WHERE NOT EXISTS ( SELECT MB.MALOAI
					FROM MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX ='Airbus'
					EXCEPT 
					SELECT KN.MALOAI
					FROM KHANANG KN
					WHERE KN.MANV= NV.MANV)
-- NOT EXISTS 

	
SELECT NV.MANV, NV.TEN
FROM NHANVIEN NV
WHERE NOT EXISTS ( SELECT *
					FROM MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX ='Airbus'
					AND NOT EXISTS ( 
					SELECT *
					FROM KHANANG KN
					WHERE KN.MANV= NV.MANV AND MB.MALOAI=KN.MALOAI)	)	

--COUNT 
SELECT NV.MANV, NV.TEN
FROM NHANVIEN NV, MAYBAY MB, LOAIMB LMB, KHANANG KN
WHERE NV.MANV = KN.MANV AND KN.MALOAI = LMB.MALOAI AND LMB.MALOAI = MB.MALOAI AND LMB.HANGSX = 'Airbus'
GROUP BY NV.MANV, NV.TEN 
HAVING COUNT( DISTINCT LMB.MALOAI) = ( SELECT COUNT( DISTINCT LMB.MALOAI)
					FROM MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX ='Airbus')

--Q53 
--EXCEPT 
SELECT NV.TEN
FROM NHANVIEN NV
WHERE NV.LOAINV  =0 AND
NOT EXISTS ( SELECT CB.MACB
					FROM CHUYENBAY CB
					WHERE CB.MACB =100
					EXCEPT 
					SELECT PC.MACB
					FROM PHANCONG PC
					WHERE PC.MANV = NV.MANV)
--EXISTS 
SELECT NV.TEN
FROM NHANVIEN NV
WHERE NV.LOAINV  =0 AND
NOT EXISTS ( SELECT *
					FROM CHUYENBAY CB
					WHERE CB.MACB =100
					AND NOT EXISTS ( 
					SELECT *
					FROM PHANCONG PC
					WHERE PC.MANV = NV.MANV AND CB.MACB = PC.MACB))

--COUNT 
SELECT NV.TEN
FROM NHANVIEN NV, CHUYENBAY CB, PHANCONG PC
WHERE NV.LOAINV  =0 AND NV.MANV = PC.MANV AND PC.MACB = CB.MACB AND CB.MACB =100
GROUP BY NV.TEN, NV.MANV
HAVING COUNT(DISTINCT CB.MACB) = (SELECT COUNT(*)
					FROM CHUYENBAY CB
					WHERE CB.MACB =100)

--Q54
--EXCEPT
SELECT LB.NGAYDI
FROM LICHBAY LB
WHERE NOT EXISTS (  SELECT MB.SOHIEU
					FROM	MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX = 'Boeing'
					EXCEPT 
					SELECT LB2.SOHIEU
					FROM	 LICHBAY LB2
					WHERE	LB2.MACB = LB.MACB )


--NOT EXISTS 
SELECT LB.NGAYDI
FROM LICHBAY LB
WHERE NOT EXISTS (  SELECT *
					FROM	MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX = 'Boeing'
					AND NOT EXISTS ( 
					SELECT *
					FROM	 LICHBAY LB2
					WHERE	LB2.MACB = LB.MACB AND MB.SOHIEU = LB2.SOHIEU))
--COUNT 

SELECT LB.NGAYDI
FROM LICHBAY LB, MAYBAY MB, LOAIMB LMB 
WHERE LB.SOHIEU = MB.SOHIEU AND MB.MALOAI	=LMB.MALOAI AND LMB.HANGSX = 'Boeing'
GROUP BY LB.NGAYDI, LB.MACB
HAVING COUNT (DISTINCT LMB.MALOAI) = (SELECT COUNT(*)
					FROM	MAYBAY MB, LOAIMB LMB
					WHERE MB.MALOAI = LMB.MALOAI AND LMB.HANGSX = 'Boeing')

