-- =============================================
-- Author:		Trần Quốc Bảo
-- ID:			1512029
-- Create date: 4/12/2017
-- Description:	Cuối kì
-- =============================================

-- Câu 1
SELECT * FROM GIAOVIEN WHERE DIACHI LIKE N'%TP HCM'

-- Câu 2
SELECT * FROM GIAOVIEN LEFT JOIN NGUOITHAN ON GIAOVIEN.MAGV = NGUOITHAN.MAGV

-- Câu 3
SELECT *
FROM GIAOVIEN
WHERE MAGV IN
(SELECT MAGV
FROM NGUOITHAN
GROUP BY MAGV
HAVING COUNT(*) >= 2)

-- Câu 4
SELECT *
FROM GIAOVIEN
WHERE (PHAI = N'Nam' AND (YEAR(GETDATE()) - YEAR(NGSINH)) > 60) OR (PHAI = N'Nữ' AND (YEAR(GETDATE()) - YEAR(NGSINH)) > 55)

-- Câu 5
SELECT BM.*, SL.SLGV
FROM BOMON BM LEFT JOIN
(
SELECT MABM, COUNT(MAGV) AS SLGV
FROM GIAOVIEN
WHERE NOT(PHAI = N'Nam' AND (YEAR(GETDATE()) - YEAR(NGSINH)) > 60) AND NOT(PHAI = N'Nữ' AND (YEAR(GETDATE()) - YEAR(NGSINH)) > 55)
GROUP BY MABM
) AS SL
ON BM.MABM = SL.MABM

-- Câu 6
DELETE FROM NGUOITHAN
WHERE MAGV IN
(SELECT MAGV
FROM GIAOVIEN
WHERE (PHAI = N'Nam' AND (YEAR(GETDATE()) - YEAR(NGSINH)) > 60) OR (PHAI = N'Nữ' AND (YEAR(GETDATE()) - YEAR(NGSINH)) > 55)
)

-- Câu 7
SELECT *
FROM GIAOVIEN GV
WHERE NOT EXISTS
(
SELECT MADT
FROM DETAI
EXCEPT
SELECT TG.MADT
FROM THAMGIADT TG
WHERE GV.MAGV = TG.MAGV
)

-- Câu 8
SELECT *
FROM GIAOVIEN
WHERE MABM = N'VS' AND MAGV IN
(
SELECT TG.MAGV
FROM GIAOVIEN GV, THAMGIADT TG, DETAI DT
WHERE GV.MAGV = TG.MAGV AND TG.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY TG.MAGV, TG.MADT
HAVING COUNT(TG.STT) = 
(
SELECT COUNT(CV.SOTT) 
FROM CONGVIEC CV, DETAI DT 
WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
GROUP BY CV.MADT
))

-- Câu 9
SELECT *
FROM GIAOVIEN GV
WHERE GV.MABM = N'VS' AND NOT EXISTS
(
SELECT *
FROM CONGVIEC CV, DETAI DT
WHERE CV.MADT = DT.MADT AND DT.TENDT = N'Nghiên cứu tế bào gốc'
AND NOT EXISTS
(
SELECT *
FROM THAMGIADT TG
WHERE TG.MAGV = GV.MAGV AND TG.MADT = DT.MADT AND TG.STT = CV.SOTT
))

-- Câu 10
CREATE PROCEDURE sp_ThemThanNhan @MaGV varchar(9), @Ten nvarchar(30), @NgSinh date, @Phai nvarchar(3)
AS
BEGIN
	DECLARE @check bit
	SET @check = 1

	IF (NOT EXISTS(SELECT * FROM GIAOVIEN WHERE MAGV = @MaGV))
	BEGIN
		SET @check = 0
		PRINT N'Lỗi! Mã giáo viên không tồn tại!'
	END

	IF (EXISTS(SELECT * FROM NGUOITHAN WHERE MAGV = @MaGV AND TEN = @Ten))
	BEGIN
		SET @check = 0
		PRINT N'Lỗi! Người thân này của giáo viên đã tồn tại!'
	END

	IF (@check = 1)
	BEGIN
		INSERT INTO NGUOITHAN(MAGV, TEN, NGSINH, PHAI)
		VALUES (@MaGV, @Ten, @NgSinh, @Phai)
		PRINT N'Thêm người thân cho giáo viên thành công!'
	END
END