/************* Bài tập tuần 5 *************/
/* Bài tập về CSDL Quản lý đề tài */
USE QuanLyDeTai
/* Q35 */
SELECT MAX(LUONG) AS Luong_Cao_Nhat
FROM GIAOVIEN

/* Q36 */
SELECT *
FROM GIAOVIEN
WHERE LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN)

/* Q37 */
SELECT MAX(LUONG) AS LUONG_CAO_NHAT_HTTT
FROM GIAOVIEN
WHERE MABM = N'HTTT'

/* Q38 */
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE YEAR(GV.NGSINH) = (SELECT MIN(YEAR(NGSINH)) FROM GIAOVIEN GV WHERE GV.MABM IN (SELECT BM.MABM FROM BOMON BM WHERE BM.TENBM = N'Hệ thống thông tin'))

/* Q39 */
SELECT GV.HOTEN
FROM GIAOVIEN GV
WHERE YEAR(GV.NGSINH) = (SELECT MAX(YEAR(NGSINH)) FROM GIAOVIEN GV WHERE GV.MABM IN (SELECT BM.MABM FROM BOMON BM WHERE BM.MAKHOA IN (SELECT MAKHOA FROM KHOA WHERE TENKHOA = N'Công nghệ thông tin')))

/* Q40 */
SELECT HOTEN, TENKHOA
FROM GIAOVIEN, KHOA, BOMON
WHERE LUONG = (SELECT MAX(LUONG) FROM GIAOVIEN) AND KHOA.MAKHOA = BOMON.MAKHOA AND BOMON.MABM = GIAOVIEN.MABM

/* Q41 */
SELECT *
FROM GIAOVIEN GV
WHERE LUONG >= ALL (SELECT LUONG FROM GIAOVIEN GV2 WHERE GV.MABM = GV2.MABM AND GV.MAGV <> GV2.MAGV)
ORDER BY GV.MABM

/* Q42 */
SELECT TENDT
FROM DETAI
WHERE MADT NOT IN (SELECT MADT FROM THAMGIADT WHERE MAGV IN ( SELECT MAGV FROM GIAOVIEN WHERE HOTEN = N'Nguyễn Hoài An'))

/* Q43 */
SELECT TENDT, HOTEN AS GVCNDT
FROM DETAI, GIAOVIEN
WHERE GIAOVIEN.MAGV = DETAI.GVCNDT AND MADT NOT IN (SELECT MADT FROM THAMGIADT WHERE MAGV IN ( SELECT MAGV FROM GIAOVIEN WHERE HOTEN = N'Nguyễn Hoài An'))

/* Q44 */
SELECT GV.HOTEN
FROM (SELECT HOTEN, MAGV FROM GIAOVIEN WHERE MABM IN (SELECT MABM FROM BOMON WHERE MAKHOA IN (SELECT MAKHOA FROM KHOA WHERE TENKHOA = N'Công nghệ thông tin'))) AS GV
WHERE GV.MAGV NOT IN (SELECT MAGV FROM THAMGIADT)

/* Q45 */
SELECT *
FROM GIAOVIEN
WHERE MAGV NOT IN (SELECT MAGV FROM THAMGIADT)

/* Q46 */
SELECT *
FROM GIAOVIEN
WHERE LUONG > (SELECT LUONG FROM GIAOVIEN WHERE GIAOVIEN.HOTEN = N'Nguyễn Hoài An')

/* Q47 */
SELECT *
FROM GIAOVIEN
WHERE MAGV IN (SELECT TRUONGBM FROM BOMON)
AND MAGV IN (SELECT MAGV FROM THAMGIADT)

/* Q48 */
SELECT *
FROM GIAOVIEN GV1
WHERE EXISTS 
(SELECT * 
FROM GIAOVIEN GV2 
WHERE GV1.HOTEN LIKE GV2.HOTEN
AND GV1.PHAI = GV2.PHAI
AND GV1.MABM = GV2.MABM
AND GV1.MAGV <> GV2.MAGV)

/* Q49 */
SELECT *
FROM GIAOVIEN
WHERE LUONG > ANY (SELECT GV.LUONG FROM GIAOVIEN GV, BOMON BM WHERE GV.MABM = BM.MABM AND BM.TENBM = N'Công nghệ phần mềm')

/* Q50 */
SELECT *
FROM GIAOVIEN
WHERE LUONG > (SELECT MAX(LUONG) FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MABM = BOMON.MABM AND BOMON.TENBM = N'Hệ thống thông tin')

/* Q51 */
SELECT KH.TENKHOA
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = KH.MAKHOA
GROUP BY KH.MAKHOA, KH.TENKHOA
HAVING COUNT(*) >= ALL(
SELECT COUNT(*)
FROM GIAOVIEN GV, BOMON BM, KHOA KH
WHERE GV.MABM = BM.MABM AND BM.MAKHOA = KH.MAKHOA
GROUP BY KH.MAKHOA)

/* Q52 */
SELECT HOTEN
FROM GIAOVIEN
WHERE GIAOVIEN.MAGV IN
(SELECT GVCNDT
FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT))

/* Q53 */
SELECT MABM
FROM GIAOVIEN
GROUP BY MABM
HAVING COUNT(*) >= ALL(SELECT COUNT(*) FROM GIAOVIEN GROUP BY MABM)

/* Q54 */
SELECT HOTEN, TENBM
FROM GIAOVIEN GV, BOMON BM
WHERE BM.MABM = GV.MABM AND GV.MAGV IN 
(SELECT MAGV
FROM THAMGIADT
GROUP BY MAGV
HAVING COUNT(DISTINCT MADT) >= ALL (SELECT COUNT (DISTINCT MADT) FROM THAMGIADT GROUP BY MAGV))

/* Q55 */
SELECT HOTEN
FROM GIAOVIEN GV, THAMGIADT DT
WHERE GV.MAGV = DT.MAGV AND GV.MABM = N'HTTT'
GROUP BY GV.MAGV, GV.HOTEN
HAVING COUNT(DISTINCT DT.MADT) >= ALL(SELECT COUNT(DISTINCT THAMGIADT.MADT) FROM THAMGIADT WHERE GV.MAGV = THAMGIADT.MAGV GROUP BY THAMGIADT.MAGV)

/* Q56 */
SELECT *
FROM GIAOVIEN
WHERE MAGV IN
(SELECT MAGV
FROM NGUOITHAN
GROUP BY MAGV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM NGUOITHAN GROUP BY MAGV))

/* Q57 */
SELECT HOTEN
FROM GIAOVIEN, BOMON
WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND GIAOVIEN.MAGV IN
(SELECT GVCNDT
FROM DETAI
GROUP BY GVCNDT
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DETAI GROUP BY GVCNDT))

/* Bài tập về CSDL Quản lý chuyến bay */
USE QuanLyChuyenBay
/* Q34 */
SELECT LB.SOHIEU, LB.MALOAI, MB.HANGSX
FROM LICHBAY LB, LOAIMB MB
WHERE LB.MALOAI = MB.MALOAI
GROUP BY LB.SOHIEU, LB.MALOAI, MB.HANGSX
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM LICHBAY LB, LOAIMB MB WHERE LB.MALOAI = MB.MALOAI GROUP BY LB.SOHIEU, LB.MALOAI, MB.HANGSX)

/* Q35 */
SELECT TEN
FROM NHANVIEN
WHERE MANV IN
(SELECT MANV
FROM PHANCONG
GROUP BY MANV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM PHANCONG GROUP BY MANV))

/* Q36 */
SELECT NV.TEN, NV.DCHI, NV.DTHOAI
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.LOAINV = 1 AND NV.MANV = PC.MANV
GROUP BY NV.MANV, NV.TEN, NV.DCHI, NV.DTHOAI
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM NHANVIEN NV, PHANCONG PC WHERE NV.LOAINV = 1 AND NV.MANV = PC.MANV GROUP BY NV.MANV)

/* Q37 */
SELECT SBDEN, COUNT(MACB) AS SL
FROM CHUYENBAY
GROUP BY SBDEN
HAVING COUNT(MACB) <= ALL (SELECT COUNT(*) FROM CHUYENBAY GROUP BY SBDEN)

/* Q38 */
SELECT SBDI, COUNT(MACB) AS SL
FROM CHUYENBAY
GROUP BY SBDI
HAVING COUNT(MACB) >= ALL (SELECT COUNT(*) FROM CHUYENBAY GROUP BY SBDI)

/* Q39 */
SELECT TEN, DCHI, DTHOAI
FROM KHACHHANG
WHERE MAKH IN
(SELECT MAKH
FROM DATCHO
GROUP BY MAKH
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM DATCHO GROUP BY MAKH))

/* Q40 */
SELECT MANV, TEN, LUONG
FROM NHANVIEN
WHERE MANV IN
(SELECT MANV
FROM KHANANG
GROUP BY MANV
HAVING COUNT(*) >= ALL (SELECT COUNT(*) FROM KHANANG GROUP BY MANV))

/* Q41 */
SELECT MANV, TEN, LUONG
FROM NHANVIEN
WHERE LUONG = (SELECT MAX(LUONG) FROM NHANVIEN)

/* Q42 */ /* Vì trong một phi hành đoàn cho nên xuất ra phi hành đoán mà nhân viên có lương cao nhất đó tham gia */
SELECT NV.TEN, NV.DCHI, PC.MACB, PC.NGAYDI 
FROM NHANVIEN NV, PHANCONG PC
WHERE NV.MANV = PC.MANV AND NV.LUONG = (SELECT MAX(LUONG) FROM NHANVIEN NV1, PHANCONG PC1 WHERE NV1.MANV = PC1.MANV AND PC.MACB = PC1.MACB AND PC.NGAYDI = PC1.NGAYDI GROUP BY PC1.MACB, PC1.NGAYDI)

/* Q43 */
SELECT MACB, GIODI, GIODEN
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, GIODI, (SELECT MIN(GIODI) FROM CHUYENBAY)) = 0

/* Q44 */
SELECT MACB, CAST(DATEADD(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN), 0) AS TIME) AS TG_BAY
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN), (SELECT MAX(DATEDIFF(MINUTE, GIODI, GIODEN)) FROM CHUYENBAY)) = 0

/* Q45 */
SELECT MACB, CAST(DATEADD(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN), 0) AS TIME) AS TG_BAY
FROM CHUYENBAY
WHERE DATEDIFF(MINUTE, DATEDIFF(MINUTE, GIODI, GIODEN), (SELECT MIN(DATEDIFF(MINUTE, GIODI, GIODEN)) FROM CHUYENBAY)) = 0

/* Q46 */
SELECT MACB, NGAYDI
FROM LICHBAY
WHERE MACB IN
(
SELECT MACB
FROM LICHBAY
WHERE MALOAI = 'B747'
GROUP BY MACB
HAVING COUNT(NGAYDI) >= ALL (SELECT COUNT(NGAYDI) FROM LICHBAY WHERE MALOAI ='B747' GROUP BY MACB)
)

/* Q47 */
SELECT PC.MACB, PC.NGAYDI, COUNT(MANV) AS SL_NV
FROM PHANCONG PC,
(
SELECT MACB, NGAYDI
FROM DATCHO
GROUP BY MACB, NGAYDI
HAVING COUNT(MAKH) > 3
) AS KH
WHERE PC.MACB = KH.MACB AND PC.NGAYDI = KH.NGAYDI
GROUP BY PC.MACB, PC.NGAYDI

/* Q48 */
SELECT LOAINV, COUNT(MANV)
FROM NHANVIEN
GROUP BY LOAINV
HAVING SUM(LUONG) > 600000

/* Q49 */
SELECT DC.MACB, DC.NGAYDI, COUNT(MAKH) AS SL_KH
FROM DATCHO DC, 
(
SELECT MACB, NGAYDI
FROM PHANCONG
GROUP BY MACB, NGAYDI
HAVING COUNT(MANV) > 3
) AS PC
WHERE PC.MACB = DC.MACB AND PC.NGAYDI = DC.NGAYDI
GROUP BY DC.MACB, DC.NGAYDI

/* Q50 */
SELECT MALOAI, COUNT(SOHIEU) AS SL_CHUYENBAY
FROM LICHBAY
WHERE MALOAI IN
(
SELECT MALOAI
FROM MAYBAY
GROUP BY MALOAI
HAVING COUNT(SOHIEU) > 1
)
GROUP BY MALOAI