/* Câu 1 */
SELECT DISTINCT NHANVIEN.MANV, NHANVIEN.TEN AS TEN_PHI_CONG, NHANVIEN.DCHI, NHANVIEN.DTHOAI
FROM NHANVIEN, PHANCONG, LICHBAY
WHERE NHANVIEN.LOAINV = 1 AND NHANVIEN.MANV = PHANCONG.MANV AND PHANCONG.MACB = LICHBAY.MACB AND LICHBAY.MALOAI = 'B747'

/* Câu 2 */
SELECT CHUYENBAY.MACB, LICHBAY.NGAYDI FROM CHUYENBAY, LICHBAY WHERE CHUYENBAY.SBDI = 'DCA' AND CHUYENBAY.MACB = LICHBAY.MACB AND DATEDIFF(MINUTE, CHUYENBAY.GIODI, '14:00') <= 0 AND DATEDIFF(MINUTE, CHUYENBAY.GIODI, '18:00') >= 0

/* Câu 3 */
SELECT DISTINCT NHANVIEN.TEN FROM NHANVIEN, PHANCONG, CHUYENBAY WHERE NHANVIEN.MANV = PHANCONG.MANV AND PHANCONG.MACB = '100' AND CHUYENBAY.MACB = PHANCONG.MACB AND CHUYENBAY.SBDI = 'SLC'

/* Câu 4 */
SELECT DISTINCT LICHBAY.MALOAI, LICHBAY.SOHIEU FROM LICHBAY, CHUYENBAY
WHERE CHUYENBAY.MACB = LICHBAY.MACB AND CHUYENBAY.SBDI = 'MIA'

/* Câu 5 */
SELECT DATCHO.MACB, DATCHO.NGAYDI, KHACHHANG.TEN, KHACHHANG.DCHI, KHACHHANG.DTHOAI
FROM DATCHO, KHACHHANG
WHERE DATCHO.MAKH = KHACHHANG.MAKH
ORDER BY DATCHO.MACB ASC, DATCHO.NGAYDI DESC

/* Câu 6 */
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, NHANVIEN.TEN, NHANVIEN.DCHI, NHANVIEN.DTHOAI
FROM NHANVIEN, PHANCONG
WHERE NHANVIEN.MANV = PHANCONG.MANV
ORDER BY PHANCONG.MACB ASC, PHANCONG.NGAYDI DESC

/* Câu 7 */
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, NHANVIEN.MANV, NHANVIEN.TEN AS TEN_PHI_CONG
FROM PHANCONG, NHANVIEN, CHUYENBAY
WHERE NHANVIEN.LOAINV = 1 AND NHANVIEN.MANV = PHANCONG.MANV AND PHANCONG.MACB = CHUYENBAY.MACB AND CHUYENBAY.SBDEN = 'ORD'

/* Câu 8 */
SELECT PHANCONG.MACB, PHANCONG.NGAYDI, NHANVIEN.TEN AS TEN_PHI_CONG
FROM PHANCONG, NHANVIEN
WHERE NHANVIEN.MANV = '1001' AND NHANVIEN.LOAINV = 1 AND NHANVIEN.MANV = PHANCONG.MANV

/* Câu 9 */
SELECT CHUYENBAY.MACB, CHUYENBAY.SBDI, CHUYENBAY.GIODI, CHUYENBAY.GIODEN, LICHBAY.NGAYDI
FROM CHUYENBAY, LICHBAY
WHERE CHUYENBAY.SBDEN = 'DEN' AND CHUYENBAY.MACB = LICHBAY.MACB
ORDER BY LICHBAY.NGAYDI DESC, CHUYENBAY.SBDI ASC

/* Câu 10 */
SELECT NHANVIEN.TEN AS TEN_PHI_CONG, LOAIMB.HANGSX, LOAIMB.MALOAI
FROM NHANVIEN, KHANANG, LOAIMB
WHERE NHANVIEN.LOAINV = 1 AND NHANVIEN.MANV = KHANANG.MANV AND KHANANG.MALOAI = LOAIMB.MALOAI

/* Câu 11 */
SELECT DISTINCT NHANVIEN.MANV, NHANVIEN.TEN AS TEN_PHI_CONG
FROM NHANVIEN, PHANCONG
WHERE NHANVIEN.LOAINV = 1 AND NHANVIEN.MANV = PHANCONG.MANV AND PHANCONG.MACB = '100' AND DATEDIFF(D, PHANCONG.NGAYDI, '11/01/2000') = 0

/* Câu 12 */
SELECT CHUYENBAY.MACB, NHANVIEN.MANV, NHANVIEN.TEN
FROM CHUYENBAY, NHANVIEN, PHANCONG
WHERE DATEDIFF(D, PHANCONG.NGAYDI, '10/31/2000') = 0 AND CHUYENBAY.SBDI = 'MIA' AND DATEDIFF(M, CHUYENBAY.GIODI, '20:30') = 0 AND NHANVIEN.MANV = PHANCONG.MANV AND PHANCONG.MACB = CHUYENBAY.MACB

/* Câu 13 */
SELECT PHANCONG.MACB, LICHBAY.SOHIEU, LICHBAY.MALOAI, LOAIMB.HANGSX
FROM NHANVIEN, PHANCONG, LICHBAY, LOAIMB
WHERE NHANVIEN.LOAINV = 1 AND NHANVIEN.TEN = N'Quang' AND NHANVIEN.MANV = PHANCONG.MANV AND PHANCONG.MACB = LICHBAY.MACB AND LOAIMB.MALOAI = LICHBAY.MALOAI AND DATEDIFF(D, PHANCONG.NGAYDI, LICHBAY.NGAYDI) = 0

/* Câu 14 */
SELECT DISTINCT NHANVIEN.TEN
FROM NHANVIEN, PHANCONG
WHERE NHANVIEN.LOAINV = 1 AND NHANVIEN.MANV NOT IN (SELECT PHANCONG.MANV FROM PHANCONG)

/* Câu 15 */
SELECT DISTINCT KHACHHANG.TEN AS KH_DA_DI_BOEING
FROM KHACHHANG, DATCHO, LICHBAY, LOAIMB
WHERE  KHACHHANG.MAKH = DATCHO.MAKH AND (DATCHO.MACB = LICHBAY.MACB AND DATEDIFF(D, DATCHO.NGAYDI, LICHBAY.NGAYDI) = 0) AND (LICHBAY.MALOAI = LOAIMB.MALOAI AND LOAIMB.HANGSX = 'Boeing')

/* Câu 16 */
SELECT DISTINCT LICHBAY.MACB
FROM LICHBAY
WHERE LICHBAY.SOHIEU = '10' AND LICHBAY.MALOAI = 'B747'