/* Câu 1 */
SELECT HOTEN, LUONG FROM GIAOVIEN WHERE PHAI = N'Nữ'

/* Câu 2 */
SELECT HOTEN, LUONG AS LUONG_TRUOC, LUONG*1.1 AS LUONG_SAU FROM GIAOVIEN

/* Câu 3 */
SELECT MAGV FROM GIAOVIEN, BOMON WHERE (GIAOVIEN.LUONG > 2000 AND GIAOVIEN.HOTEN LIKE N'Nguyễn%') OR (BOMON.TRUONGBM = GIAOVIEN.MAGV AND YEAR(BOMON.NGAYNHANCHUC) > 1995)

/* Câu 4 */
SELECT HOTEN FROM GIAOVIEN, BOMON, KHOA WHERE GIAOVIEN.MABM = BOMON.MABM AND BOMON.MAKHOA = KHOA.MAKHOA AND KHOA.TENKHOA = N'Công nghệ thông tin'

/* Câu 5 */
SELECT * FROM BOMON LEFT JOIN GIAOVIEN ON GIAOVIEN.MAGV = BOMON.TRUONGBM

/* Câu 6 */
SELECT * FROM GIAOVIEN LEFT JOIN BOMON ON GIAOVIEN.MABM = BOMON.MABM

/* Câu 7 */
SELECT DETAI.TENDT, GIAOVIEN.* FROM DETAI LEFT JOIN GIAOVIEN ON GIAOVIEN.MAGV = DETAI.GVCNDT

/* Câu 8 */
SELECT * FROM KHOA, GIAOVIEN WHERE GIAOVIEN.MAGV = KHOA.TRUONGKHOA

/* Câu 9 */
SELECT DISTINCT GIAOVIEN.* FROM GIAOVIEN, THAMGIADT, BOMON WHERE THAMGIADT.MADT = '006' AND GIAOVIEN.MAGV = THAMGIADT.MAGV AND GIAOVIEN.MABM = BOMON.MABM AND BOMON.TENBM = N'Vi sinh'

/* Câu 10 */
SELECT DETAI.MADT, CHUDE.*, GIAOVIEN.HOTEN, GIAOVIEN.NGSINH, GIAOVIEN.DIACHI
FROM DETAI, CHUDE, GIAOVIEN
WHERE DETAI.CAPQL = N'Thành phố' AND DETAI.MACD = CHUDE.MACD AND DETAI.GVCNDT = GIAOVIEN.MAGV

/* Câu 11 */
SELECT * FROM GIAOVIEN A LEFT JOIN GIAOVIEN B ON A.MAGV = B.GVQLCM

/* Câu 12 */
SELECT A.HOTEN FROM GIAOVIEN A WHERE A.GVQLCM = (SELECT GIAOVIEN.MAGV FROM GIAOVIEN WHERE GIAOVIEN.HOTEN = N'Nguyễn Thanh Tùng') 

/* Câu 13 */
SELECT GIAOVIEN.HOTEN FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND BOMON.TENBM = N'Hệ thống thông tin'

/* Câu 14 */
SELECT DISTINCT GIAOVIEN.HOTEN FROM GIAOVIEN, DETAI, THAMGIADT, CHUDE WHERE (DETAI.MADT = THAMGIADT.MADT AND THAMGIADT.MAGV = GIAOVIEN.MAGV) AND (DETAI.MACD = CHUDE.MACD AND CHUDE.TENCD = N'Quản lý giáo dục')

/* Câu 15 */
SELECT DISTINCT CONGVIEC.TENCV FROM CONGVIEC, DETAI WHERE (CONGVIEC.MADT = DETAI.MADT AND DETAI.TENDT = N'HTTT quản lý các trường ĐH') AND datediff(m, CONGVIEC.NGAYBD, '3/1/2008') = 0

/* Câu 16 */
SELECT A.HOTEN AS HOTEN_GV, B.HOTEN AS HOTEN_GVGLCM FROM GIAOVIEN A LEFT JOIN GIAOVIEN B ON B.MAGV = A.GVQLCM

/* Câu 17 */
SELECT * FROM CONGVIEC WHERE DATEDIFF(d, CONGVIEC.NGAYBD, '1/1/2007') < 0 AND DATEDIFF(d, CONGVIEC.NGAYBD, '8/1/2007') > 0

/* Câu 18 */
SELECT DISTINCT GIAOVIEN.HOTEN FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MABM = (SELECT BOMON.MABM FROM GIAOVIEN, BOMON WHERE BOMON.MABM = GIAOVIEN.MABM AND GIAOVIEN.HOTEN = N'Trần Trà Hương') AND GIAOVIEN.HOTEN != N'Trần Trà Hương'

/* Câu 19 */
SELECT DISTINCT GIAOVIEN.* FROM GIAOVIEN, DETAI, KHOA WHERE GIAOVIEN.MAGV = KHOA.TRUONGKHOA AND GIAOVIEN.MAGV = DETAI.GVCNDT

/* Câu 20 */
SELECT GIAOVIEN.HOTEN FROM GIAOVIEN, BOMON, KHOA WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND GIAOVIEN.MAGV = KHOA.TRUONGKHOA

/* Câu 21 */
SELECT DISTINCT GIAOVIEN.HOTEN FROM GIAOVIEN, DETAI, BOMON WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM AND GIAOVIEN.MAGV = DETAI.GVCNDT

/* Câu 22 */
SELECT DISTINCT GIAOVIEN.MAGV FROM GIAOVIEN, DETAI, KHOA WHERE GIAOVIEN.MAGV = KHOA.TRUONGKHOA AND GIAOVIEN.MAGV = DETAI.GVCNDT

/* Câu 23 */
SELECT DISTINCT GIAOVIEN.MAGV FROM GIAOVIEN, BOMON, THAMGIADT WHERE (GIAOVIEN.MABM = N'HTTT') OR (GIAOVIEN.MAGV = THAMGIADT.MAGV AND THAMGIADT.MADT = '001')

/* Câu 24 */
SELECT GIAOVIEN.* FROM GiAOVIEN WHERE GIAOVIEN.MABM = (SELECT GIAOVIEN.MABM FROM GIAOVIEN WHERE GIAOVIEN.MAGV = '002') AND GIAOVIEN.MAGV != '002'

/* Câu 25 */
SELECT GIAOVIEN.* FROM GIAOVIEN, BOMON WHERE GIAOVIEN.MAGV = BOMON.TRUONGBM

/* Câu 26 */
SELECT HOTEN, LUONG FROM GIAOVIEN